version: 2
jobs:
  build-test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Make locally
          command: make all
      - run:
          name: Generate test reports
          command: |
            make report
            mkdir -p /tmp/artifacts
            cp cp.out coverage.html .cache/test_coverage_total.txt /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Build release artifacts
          command: make dist
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish-docker-image:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to docker
          command: make docker-login
      - run:
          name: Build and push docker image
          command: make docker-all

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-docker-image:
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
